### ISSUE TITLE
Does the callback happen once the zip file is ready to use?

### ISSUE THREAD

**Issue by polishdude20** [maugenst/zip-a-folder#11]
I'm trying to use zip-a-folder to zip a bunch of files when a request to a server comes in and on the callback, send the zip file to the client. For some reason, sometimes I get a zip file that is 0 bytes. Does the zip callback happen when the file is ready to be used? Or am I missing something else?

**Comment by maugenst** [comment]
Hi 

I'm using the stream API on nodes fs.createWriteStream to call the callback function when the stream closes:

`
var output = fs.createWriteStream(zipFilePath);
output.on('close', function() {
                    callback();
                });
`

By now I cannot see any problems here. Which version of node are you using? Is this also reproducible on other versions?

BR, Marius

**Comment by polishdude20** [comment]
Hi Marius,

It seems like the problem was on my end.

**Comment by maugenst** [comment]
No problem :-) ... take care!

**Comment by aronduby** [comment]
Incase anyone else out there lands here 5+ years later because you have a similar problem, remember that the `forEach` method of looping does't play nicely with async/await.

```js
// 🚫 nope
folders.forEach(async (folder) => await zip(folder, './dest'));

// ✔ yup
(async function() {
    for (const folder of folders) {
        await zip(folder, './dest');
    }
})();
```
