### ISSUE TITLE
Skip Files & Folders?

### ISSUE THREAD

**Issue by ivanjeremic** [maugenst/zip-a-folder#15]
Is it possible to implement to Skip/exclude files & Folder inside the folder we want to zip?

**Comment by maugenst** [comment]
Hm... Interesting idea. How would you name the files? Regex? Globs? Whitelists?

Drop me an idea on how to extend the API...

**Comment by bigman73** [comment]
Zip a folder is a wrapper around Archiver and it supports globs.

**Comment by maugenst** [comment]
I overthought the idea and came to the conclusion that I will to not support this. Here are my two cents on this. 

Archiver uses the globs to identify files to be added to an archive (https://www.archiverjs.com/docs/archiver#glob) or a whole directory (https://www.archiverjs.com/docs/archiver#directory).

Here we come to the point where is simply doesn't make sense to wrap a funktionality that an other library already handles. zip-a-folder intentionally was created to simply (as the name states) **zip a folder**. So from my pov if you want to iterate on files use archiver directly.

Drop me a reply if you agree. BR

**Comment by bigman73** [comment]
I don't agree with your approach.
A simple zip a folder function should allow to simply ignore or include certain files.
It's one more optional parameter that adds a lot of value, for a common use case.

**Comment by maugenst** [comment]
Hi bigman73.

Hm ... an easy and fast forward way on this could be the following: 

Current API: 
`zip(srcFolder: string, zipFilePath: string | undefined, zipAFolderOptions?: ZipAFolderOptions)`

Proposal:
`zip(srcFolder: PathLikeString | Glob, zipFilePath: string | undefined, zipAFolderOptions?: ZipAFolderOptions)`

This would not break the current implementation. What do you think?

BRM

**Comment by maugenst** [comment]
Globs are handled from version 2.0 on.
