### ISSUE TITLE
version 0.0.13 release

### ISSUE THREAD

**Issue by code4muktesh** [maugenst/zip-a-folder#20]
when we can expect version 0.0.13 release?

**Comment by maugenst** [comment]
Which features are you missing? 

There are a few on my bucketlist, but I would appreciate your feedback very much or even better, your help ;-) ...

In the meantime I will work on enabling zip-a-folder on typescript.

**Comment by code4muktesh** [comment]
We need a version with latest versions of dependencies(archiver,jest etc) so could you please make release for the same and target the typescript migrate in later versions?

**Comment by maugenst** [comment]
There is no need to use typescript. Latest version is also usable in Vanilla JS...
