### ISSUE TITLE
Unable to handle permission error.

### ISSUE THREAD

**Issue by karan0405** [maugenst/zip-a-folder#21]
I purposely made a file impermissible and tried to compress the parent file. I am unable to catch the error with a promise catch. 
If this is not how you explicitly want it to happen, here's a simple solution @ line no 35 - 

`// Error while compressing the folder and writing to directory
    zipArchive.on("error", function (err) { 
        return callback(err); 
    });`

**Comment by maugenst** [comment]
Hi ..

I'm currently rewriting it and thankfully to you, I'll take care of it!

I'll keep you updated on this...

**Comment by maugenst** [comment]
Hi karan0405.

Please give the latest version 1.0.0 a shot and get back to me if you encounter problems.

Best regards

**Comment by karan0405** [comment]
Hi @maugenst,

Zip-a-folder still points to unmodified file - "dist/lib/ZipAFolder.js". I see the same error here. Let me know if I am wrong here.

Thanks

**Comment by maugenst** [comment]
Hi @karan0405 

version 1.0.1 should have the builded version in place. please give it a try and get back to me.

BR
