### ISSUE TITLE
Extra dependencies in published package

### ISSUE THREAD

**Issue by Xotabu4** [maugenst/zip-a-folder#22]
I noticed that this package installs 
+ zip-a-folder@1.0.0
added 297 packages from 243 contributors and audited 318 packages in 18.739s

297 is way to much, probably thats because of extra packages specified in "dependencies"

  "dependencies": {
    should be devDependencies - "@types/archiver": "^5.1.0",
    should be devDependencies - "@types/jest": "^26.0.20",
    should be devDependencies - "@types/node": "^14.14.33",
    "archiver": "^5.0.0",
    should be devDependencies -  "jest-extended": "^0.11.5",
    should be devDependencies - "ts-jest": "^26.5.3",
    should be devDependencies - "tslint": "^6.1.3",
    should be devDependencies - "tslint-plugin-prettier": "^2.3.0",
    should be devDependencies - "typescript": "^4.2.3"
  }

**Comment by Xotabu4** [comment]
@maugenst Hi, prepared a PR, what do you think about it?

**Comment by maugenst** [comment]
Thank you very much!

I'll take care and merge your PR!
