### ISSUE TITLE
Whitelist directory

### ISSUE THREAD

**Issue by Armaldio** [maugenst/zip-a-folder#3]
Hello, 

Is there any way to exclude a folder from the zipping process ? (built-in or not)

Thanks

**Comment by maugenst** [comment]
Hi Armaldio.

No, there is currently no plan to white- or blacklist directories or files. Although it could be possible, but currently the plan is to keep the tool as simple as possible. Zip a folder. Nothing more. 

For all other use cases I would rather recommend to use the underlying archiver directly.

Thanks, Marius
