### ISSUE TITLE
What's the default compression level for `^1.1.0` if not provided?

### ISSUE THREAD

**Issue by wenfangdu** [maugenst/zip-a-folder#31]
Looking at the code, I think it's `COMPRESSION_LEVEL.high` for `v1.1.0`. IIRC, `COMPRESSION_LEVEL.uncompressed` was the default for `v1.0.1`, will `COMPRESSION_LEVEL.high` stay the default for `^v1.1.0`?

If so, I'm just going to omit this parameter :).

https://github.com/maugenst/zip-a-folder/blob/58ad44245f0d8bdd0c28a39ef5d53e705ae5be34/lib/ZipAFolder.ts#L56

Also, I think the default `ZipAFolderOptions` should be reflected in the doc as well, something like "if not provided, defaults to `{ compression: COMPRESSION_LEVEL.high }`, that would be very helpful for newcomers.

**Comment by maugenst** [comment]
latest version 1.1.1 has added README docu as well as method docu so your IDE can provide this when mouse-hovering over the method...
