### ISSUE TITLE
big folder not working

### ISSUE THREAD

**Issue by huonghope** [maugenst/zip-a-folder#32]

**Comment by maugenst** [comment]
Could you please give some more details about the error happening?

**Comment by GrosSacASac** [comment]
Same, 
folder has 578MB, 114 images,
it creates error_file.zip
with error_file inside
the promise never resolves

**Comment by maugenst** [comment]
Added a test to latest version. Works pretty well with a folder containing 410 images with a total size of 1.8 GB ...

Please prepare this test as described and rerun it on your side.
