### ISSUE TITLE
[Need Help] i'm getting error in throw new Error(`Permission error: ${e.message}`);

### ISSUE THREAD

**Issue by wiralegawa** [maugenst/zip-a-folder#35]
hi team, thank you for creating this package, and i just use this package, but getting some issue on permission

full logs :

> /Users/ditd21240/mobile-banking-app-automation/node_modules/zip-a-folder/lib/ZipAFolder.ts:109
                throw new Error(`Permission error: ${e.message}`);
                      ^
Error: Permission error: ENOENT: no such file or directory, access '/reports'
    at Function.compress (/Users/ditd21240/utomation/node_modules/zip-a-folder/lib/ZipAFolder.ts:109:23)
    at async zip (/Users/ditd21240/mobile-banking-app-automation/node_modules/zip-a-folder/lib/ZipAFolder.ts:70:13)
    at async CommonsUtils.zipFolder (/Users/ditd21240/mobile-banking-app-automation/tests/helpers/CommonUtils.ts:40:9)

can someone help me to solve this ?

tried with changes permision on the folder but no luck

<img width="248" alt="Screen Shot 2022-01-03 at 16 36 11" src="https://user-images.githubusercontent.com/6754795/147916383-b5870a1c-6d78-4576-81a9-cc62f7af4c9f.png">

**Comment by maugenst** [comment]
Perhaps your process is running using a different user? Regarding the provided information I do not have information about users / os / ...
 
All I can see is that your node runtime does not have access to /reports. Please check the user your process is running in and the permissions.
