### ISSUE TITLE
ENOENT occurred when zip with glob

### ISSUE THREAD

**Issue by so5** [maugenst/zip-a-folder#45]
Hi, 

I got an "ENOENT" error when making a zip file with glob.

here is a reproduction test
https://runkit.com/so5/649bd9fb79cf9d0008024fe1

I also found a bit of strange code in the distribution.
This error occurred from the following line in dist/lib/ZipAFolder.js

https://github.com/maugenst/zip-a-folder/blob/d2ea465b20dc33cf8c98c58a7acaf875c586c3e1/dist/lib/ZipAFolder.js#L73

The corresponding TS code must be
https://github.com/maugenst/zip-a-folder/blob/d2ea465b20dc33cf8c98c58a7acaf875c586c3e1/lib/ZipAFolder.ts#L121-L123

It clearly avoids calling fs.promises.access with glob.

I'm not familiar with Type script, so I'm not sure what's going on. could you take a look?

**Comment by maugenst** [comment]
Will take care after holidays.

**Comment by maugenst** [comment]
I fixed an issue in glob handling with version 2.0.1. Tests are added and working properly. 
Feel free to reopen this issue if it still occurs.
