### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by glachac-safelishare** [maugenst/zip-a-folder#48]
With the latest release today, I get the following errors when using:

```
node_modules/zip-a-folder/lib/ZipAFolder.ts:4:22 - error TS7016: Could not find a declaration file for module 'archiver'. '/home/gerry/tmp/package/node_modules/archiver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/archiver` if it exists or add a new declaration (.d.ts) file containing `declare module 'archiver';`

4 import archiver from 'archiver';
                       ~~~~~~~~~~
node_modules/zip-a-folder/lib/ZipAFolder.ts:6:20 - error TS7016: Could not find a declaration file for module 'is-glob'. '/home/gerry/tmp/package/node_modules/is-glob/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/is-glob` if it exists or add a new declaration (.d.ts) file containing `declare module 'is-glob';`
```

**Comment by maugenst** [comment]
Not sure where this comes from, but in my test project this did not happen. 

For now I released the project in version 3.0.0 which provides both, commonjs as well as esm. I'd like to ask you to rebase your code to the latest and reopen this ticket if you encounter issues.

**Comment by maugenst** [comment]
Thanks for providing your example project. Unfortunately I was not able to push a fixed version as a PR on your example project. Nonetheless I managed with this code to figure out on how to generate and export typings in a correct way. There were some side effects I was not aware of. By now I cloned your project and changed it accordingly to build successfully.

If you are interested I can create PR on your project showcasing the changes.

Leaving this Issue opened for now.

**Comment by glachac-safelishare** [comment]
Please push a PR, I would be curious to see the changes

**Comment by maugenst** [comment]
Still not possible. Don't know I I have to be in the collaborators list...

Anyhow ... It consumes too mus of time I cannot spend right now ...

Here are the changes:

main.ts
![image](https://github.com/maugenst/zip-a-folder/assets/6390135/401c8898-a3cd-4566-930c-00360fb88306)

package.json
![image](https://github.com/maugenst/zip-a-folder/assets/6390135/bc5a06bb-5af8-4f6d-bbfc-5a338ac36e81)

tsconfig.json
![image](https://github.com/maugenst/zip-a-folder/assets/6390135/a0cfb6d2-12c8-4ed1-961c-925ef212b5bb)

**Comment by maugenst** [comment]
Any news on this? Did it work out?

**Comment by glachac-safelishare** [comment]
Version 3.1.3 works now.  Thanks!

**Comment by maugenst** [comment]
Thanks for your feedback. Closing this by now.
