### ISSUE TITLE
2.0.2 breaks node apps built using 2.0.0

### ISSUE THREAD

**Issue by pkMinhas** [maugenst/zip-a-folder#49]
Introduction of type:module breaks code written with 2.0.0, thus making package.json dependencies of the format "^2.0.0" break deployments. 
Error message: require() of ES Module is not supported.

Possible fix: do not use module system in version 2.x.x, move version number to 3.x.x

**Comment by maugenst** [comment]
Converted project into hybrid project containing both, commonjs as well as esm. Bumped version to 3.0.0.
Feel free to reopen the ticket in case of any issues.
