### ISSUE TITLE
Can this be run from CLI?

### ISSUE THREAD

**Issue by ivanjaros** [maugenst/zip-a-folder#55]
I have a project that i would like put into a zip file as last build step. Is there a way this could be called from cli?

Like `npm zip-a-folder ./foo/ /foo.zip --high` ?

**Comment by maugenst** [comment]
Nice enhancement, but I think there are quiet some cli tools out there that are specialized to create zip and tar archives out of the box for all os'ses. What would be the big benefit to have a cli for zip-a-folder?

**Comment by ivanjaros** [comment]
> What would be the big benefit to have a cli for zip-a-folder?

Mainly that is is part of the project and npm script and not external dependency, so to speak. But I just wanted to know if there is support, nothing else. Thanks for the info.
