### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by xiatian12345** [maugenst/zip-a-folder#56]
when i run a test script,i got the error:
xxx/node_modules/zip-a-folder/dist/lib/cjs/ZipAFolder.js:89
                    throw new Error(`Permission error: ${e.message}`);
                          ^
Error: Permission error: Cannot read properties of undefined (reading 'R_OK')

my test script such as 
`
const { zip } = require("zip-a-folder");

class TestMe {
	static async main() {
		await zip("/Users/xx/src", "/Users/xx/srcdirzip.zip");
	}
}

TestMe.main();
`

what should i do?
Thanku!

**Comment by maugenst** [comment]
Please check your filesystem permission. The lib states, that it is not able to access the mentioned folder.
