### ISSUE TITLE
Results in much larger size then other library

### ISSUE THREAD

**Issue by flyon** [maugenst/zip-a-folder#59]
I switched to zip-a-folder today after I consistently got errors with when using `adm-zip` with big folders. Some issue further up the chain. 

So I'm very happy its working again with zip-a-folder, but did I notice that my zipped backups went up from 39Mb to 124Mb. So that's a significant difference. Any idea what can cause this and/or how compression can be improved?

**Comment by maugenst** [comment]
zip-a-folder is built on archiver.js which is using the compression implemented in https://github.com/archiverjs/node-compress-commons, while adm-zip is implementing it's own compression. 

For this project I was relying on archiver, which was the ways more stable and mature implementation. I'll have a look on the compression rates, but basically, if there are no bugs and glitches in my code (knock on wood), I cannot do much on my side to reduce the size...

Will get back to you.

**Comment by flyon** [comment]
I just switched to tar instead of zip using this library and I'm getting comparable results now. So for my use case it's no longer an issue.

**Comment by maugenst** [comment]
Final thoughts on this... 
I ran the tests locally and compression worked as expected/implemented in archiver.js:

```
drwxr-xr-x@  6 xxxxxxx xxxxxxx       192 Sep 14  2023 data
drwxr-xr-x@  2 xxxxxxx xxxxxxx        64 Sep 14  2023 folder
-rw-r--r--@  1 xxxxxxx xxxxxxx         0 Jan 10  2024 dist.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx     11029 Jan 10  2024 tests-ZipAFolder.ts
drwxr-xr-x@  3 xxxxxxx xxxxxxx        96 Nov  6 10:22 inaccessible
drwxr-xr-x@ 26 xxxxxxx xxxxxxx       832 Dec  9 17:50 ..
-rw-r--r--@  1 xxxxxxx xxxxxxx  24232398 Dec  9 17:54 testUNCOMPRESSED.zip       <----
-rw-r--r--@  1 xxxxxxx xxxxxxx    221130 Dec  9 17:54 testMEDIUM.zip       <----
-rw-r--r--@  1 xxxxxxx xxxxxxx    212570 Dec  9 17:54 testSMALL.zip       <----
-rw-r--r--@  1 xxxxxxx xxxxxxx    212570 Dec  9 17:54 test.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx    335590 Dec  9 17:54 test.destpath.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx       184 Dec  9 17:54 test.globbed.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx       152 Dec  9 17:54 test.globbed.on.the.fly.zip
drwxr-xr-x@ 25 xxxxxxx xxxxxxx       800 Dec  9 17:54 .
-rw-r--r--@  1 xxxxxxx xxxxxxx   1895786 Dec  9 17:54 test.globbed.multi.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx  24240640 Dec  9 17:54 testUNCOMPRESSED.tar
-rw-r--r--@  1 xxxxxxx xxxxxxx    220170 Dec  9 17:54 testMEDIUM.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx    211464 Dec  9 17:54 testSMALL.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx    211464 Dec  9 17:54 test.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx    335480 Dec  9 17:54 123.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx    335480 Dec  9 17:54 1234.zip
-rw-r--r--@  1 xxxxxxx xxxxxxx    215133 Dec  9 17:54 123.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx    215133 Dec  9 17:54 1234.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx   1392819 Dec  9 17:54 test.globbed.tgz
-rw-r--r--@  1 xxxxxxx xxxxxxx   1634771 Dec  9 17:54 test.globbed.multi.tgz
```
