### ISSUE TITLE
Adding parameters 

### ISSUE THREAD

**Issue by testers-123** [maugenst/zip-a-folder#7]
Hello,

Is there any way to add/set parameters to zip a folder? like, compression level : ultra , directory size 64Mb and so on.

Thanks

**Comment by maugenst** [comment]
Hi there.

It is not planned to pass in the options to the archiver library. This change would lead to an incompatible change of the API. Nonetheless it can be achieved. Please feel free to open up a Pull request with your idea on how this can be done.

Best regards, Marius

**Comment by maugenst** [comment]
Since Version 1.0 zip-a-folder has the possibillity to set compression levels. If there is an urge to expose more environment variables reopen this issue.

BR
